version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 2
    groups:
      go-modules:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 2
    groups:
      github-actions:
        patterns:
          - "*"
