apiVersion: v2
name: urgentry
description: Urgentry self-hosted Helm chart
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - urgentry
  - monitoring
  - alerting
home: https://urgentry.io
maintainers:
  - name: Urgentry Team
