apiVersion: v1
kind: Service
metadata:
  name: {{ include "urgentry.fullname" . }}-scheduler
  labels:
    {{- include "urgentry.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "urgentry.roleSelectorLabels" (dict "root" . "role" "scheduler") | nindent 4 }}
